# Test Environment Configuration
spring:
  application:
    name: school-bus-service-test
  
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    driver-class-name: org.h2.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: false
        hbm2ddl:
          import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
    database-platform: org.hibernate.dialect.H2Dialect
  
  h2:
    console:
      enabled: false

# Disable Swagger for tests
springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false

# Server Configuration
server:
  port: 0  # Random port for tests
  servlet:
    context-path: /api

# Logging Configuration - Test
logging:
  level:
    root: WARN
    com.schoolbus: INFO
    org.springframework: WARN
    org.hibernate: WARN
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

# Test specific settings
management:
  endpoints:
    enabled-by-default: false 